plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    mcpVersion = minecraft_version
    if (file('src/main/resources/META-INF/accesstransformer.cfg').exists()) {
        accessTransformers = ['src/main/resources/META-INF/accesstransformer.cfg']
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

configurations {
    webrtcBundle {
        canBeResolved = true
        canBeConsumed = true
    }
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    compileOnly group: 'org.jetbrains', name: 'annotations', version: '24.1.0'

    implementation "dev.onvoid.webrtc:webrtc-java:${webrtc_version}"
    runtimeOnly "dev.onvoid.webrtc:webrtc-java:${webrtc_version}:windows-x86_64"
    webrtcBundle "dev.onvoid.webrtc:webrtc-java:${webrtc_version}"
    webrtcBundle "dev.onvoid.webrtc:webrtc-java:${webrtc_version}:windows-x86_64"

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    testCompileClasspath.extendsFrom(modDevCompileDependencies)
    testRuntimeClasspath.extendsFrom(modDevRuntimeDependencies)
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}
