plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev'
}

neoForge {
    neoFormVersion = neo_form_version
    // Automatically enable AccessTransformers if the file exists
    def at = file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
}

configurations {
    webrtcBundle {
        canBeResolved = true
        canBeConsumed = true
    }
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
    testCompileClasspath.extendsFrom(modDevCompileDependencies)
    testRuntimeClasspath.extendsFrom(modDevRuntimeDependencies)
}

dependencies {
    compileOnly 'org.spongepowered:mixin:0.8.5'
    // fabric and neoforge both bundle mixinextras, so it is safe to use it in common
    compileOnly 'io.github.llamalad7:mixinextras-common:0.5.3'
    annotationProcessor 'io.github.llamalad7:mixinextras-common:0.5.3'

    implementation "dev.onvoid.webrtc:webrtc-java:${webrtc_version}"
    runtimeOnly "dev.onvoid.webrtc:webrtc-java:${webrtc_version}:windows-x86_64"
    webrtcBundle "dev.onvoid.webrtc:webrtc-java:${webrtc_version}"
    webrtcBundle "dev.onvoid.webrtc:webrtc-java:${webrtc_version}:windows-x86_64"

    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'io.netty:netty-transport:4.2.7.Final'
    testRuntimeOnly 'com.google.code.gson:gson:2.11.0'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}

tasks.named('jar', Jar) {
    dependsOn(configurations.webrtcBundle)
    from({
        configurations.webrtcBundle.collect { zipTree(it) }
    }) {
        exclude 'META-INF/MANIFEST.MF'
        exclude 'META-INF/*.SF'
        exclude 'META-INF/*.DSA'
        exclude 'META-INF/*.RSA'
        exclude 'fabric.mod.json'
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    }
}

// Implement mcgradleconventions loader attribute
def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each { variant ->
    configurations.named("$variant") {
        attributes {
            attribute(loaderAttribute, 'common')
        }
    }
}
sourceSets.configureEach {
    [it.compileClasspathConfigurationName, it.runtimeClasspathConfigurationName].each { variant->
        configurations.named("$variant") {
            attributes {
                attribute(loaderAttribute, 'common')
            }
        }
    }
}
